# CI jobs for the NINA chip

name: ci_nina

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - 'src/apps/**/nina/**'
      - '.github/workflows/*.yml'
    branches: [ autonomous-flie ]
  pull_request:
    branches: [ master ]

jobs:
  nina-visual-slam:  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        submodules: true
        ref: autonomous-flie    # for each app there should be a separate branch

    - name: build
      run: docker run --rm -v $PWD:/module simatai/espidf:3.3.1 /bin/bash -c "pwd; ls; ls src/apps; cd src/apps/visual-slam/nina; make clean; make all;"
    
    - name: store-nina-build
      uses: actions/upload-artifact@v2
      with:
        name: nina-firmware
        path: |
              src/apps/visual-slam/nina/build/*.bin
              src/apps/visual-slam/nina/build/bootloader/bootloader.bin
              src/apps/visual-slam/nina/build/*.elf
              src/apps/visual-slam/nina/build/*.map
